// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XWeather.iOS
{
	public partial class HourlyTvHeader : UIView
	{
		public HourlyTvHeader (IntPtr handle) : base (handle)
		{
		}

		public void SetData ()
		{
			conditionLabel.Text = null;
			dayLabel.Text = null;
			highTempLabel.Text = null;
			locationLabel.Text = null;
			lowTempLabel.Text = null;
			precipLabel.Text = null;
			tempLabel.Text = null;
			todayLabel.Text = null;

			//precipIcon.Text = null;
			//wuIcon.Text = null;
		}
	}
}
