/* This file was generated by Settings Studio
 *
 * Copyright © 2015 Colby Williams. All Rights Reserved.
 */

namespace SettingsStudio
{

	public static class SettingsKeys
	{

		#region Visible Settings


		public const string VersionNumber = "VersionNumber";

		public const string BuildNumber = "BuildNumber";

		public const string GitCommitHash = "GitCommitHash";

		public const string UserReferenceKey = "UserReferenceKey";

		public const string RandomBackgrounds = "RandomBackgrounds";

		public const string UomTemperature = "UomTemperature";


		#endregion


		#region Hidden Settings


		public const string LocationsJson = "LocationsJson";

		public const string WeatherPage = "WeatherPage";


		#endregion
	}
}