/* This file was generated by Settings Studio
 *
 * Copyright © 2015 Colby Williams. All Rights Reserved.
 */

namespace SettingsStudio
{

	public static class SettingsKeys
	{

		#region Visible Settings


		public const string ss_title_version_number = "ss_title_version_number";

		public const string ss_title_build_number = "ss_title_build_number";

		public const string ss_title_git_hash = "ss_title_git_hash";

		public const string ss_toggleswitch_first_application_launch = "ss_toggleswitch_first_application_launch";

		public const string ss_toggleswitch_logout_next_launch = "ss_toggleswitch_logout_next_launch";

		public const string ss_textfield_server_instance_url = "ss_textfield_server_instance_url";

		public const string ss_toggleswitch_allow_tracking = "ss_toggleswitch_allow_tracking";

		public const string ss_title_tracking_key = "ss_title_tracking_key";


		#endregion


		#region Hidden Settings



		#endregion
	}
}