// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XWeather.iOS
{
	public partial class DetailsTvHeader : UIView
	{
		public DetailsTvHeader (IntPtr handle) : base (handle)
		{
		}
	}
}
