/* This file was generated by Settings Studio
 *
 * Copyright © 2015 Colby Williams. All Rights Reserved.
 */

namespace SettingsStudio
{

	public static partial class Settings
	{

		#region Visible Settings


		public static string VersionNumber => StringForKey (SettingsKeys.ss_title_version_number);

		public static string BuildNumber => StringForKey (SettingsKeys.ss_title_build_number);

		public static string GitHash => StringForKey (SettingsKeys.ss_title_git_hash);

		public static string ServerInstanceUrl {
			get { return StringForKey (SettingsKeys.ss_textfield_server_instance_url); }
			set { SetSetting (SettingsKeys.ss_textfield_server_instance_url, value); }
		}

		public static string TrackingKey => StringForKey (SettingsKeys.ss_title_tracking_key);


		#endregion


		#region Hidden Settings


		public static string LocationsJson {
			get { return StringForKey (SettingsKeys.ss_string_locations_json); }
			set { SetSetting (SettingsKeys.ss_string_locations_json, value); }
		}


		#endregion
	}
}
